[package]
name = "athanor"
version="0.1.0"
edition = { workspace = true }

[dependencies]


[workspace]
resolver= "3"
members = []

[workspace.package]
edition = "2024"

[workspace.dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
